config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    self.table_name = 'subscriptions'
    self.primary_key = 'id'

    # Validations
    # @implemented
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @subscriptions = Subscription.all
    respond_with(@subscriptions)
  end

  def show
    respond_with(@subscription)
  end

  def new
    @subscription = Subscription.new
    respond_with(@subscription)
  end

  def edit
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.save
    respond_with(@subscription)
  end

  def update
    @subscription.update(subscription_params)
    respond_with(@subscription)
  end

  def destroy
    @subscription.destroy
    respond_with(@subscription)
  end

  private
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def subscription_params
      params.require(:subscription).permit(:name, :birthdate, :artistic_name, :age, :cpf, :rg, :address, :city, :phone, :email, :schooling, :experienced, :experience_description, :signature)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ALVOROÇO FILMES</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
      </ul>     
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alvoroco</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>
      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-md-4">
    <%= form.label :'Nome' %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Digite o nome', id: :subscription_name %>
    </div>
  </div>

  <div class="field col-md-4">
    <%= form.label :'Data de nascimento' %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.date_select :birthdate, class: 'form-control', required: 'required', id: :subscription_birthdate %>
    </div>
  </div>

  <div class="field col-md-4">
    <%= form.label :'Nome artistico' %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :artistic_name, class: 'form-control', required: 'required', placeholder: 'Digite o nome Artistico',
    id: :subscription_artistic_name %>
    </div>
  </div>

  <div class="field col-md-4">
    <%= form.label :'Idade' %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :age, class: 'form-control', required: 'required', placeholder: 'Digite sua idade',  id: :subscription_age %>
    </div>    
  </div>

  <div class="field col-md-4">
    <%= form.label :'CPF'.upcase %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :cpf, class: 'form-control', required: 'required', placeholder: 'Digite o CPF', id: :subscription_cpf %> 
    </div>
  </div>

  <div class="field col-md-4">
    <%= form.label :rg %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :rg, class: 'form-control', required: 'required', placeholder: 'Digite o RG', id: :subscription_rg %>
    </div>
  </div>

  <div class="field col-md-4">
    <%= form.label :'Endereço' %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :address, class: 'form-control', required: 'required', placeholder: 'Digite o Endereço', id: :subscription_address %>
    </div>
  </div>

  <div class="field col-md-4">
    <%= form.label :'Cidade' %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :city, class: 'form-control', required: 'required', placeholder: 'Digite a Cidade', id: :subscription_city %> 
    </div>
  </div>

  <div class="field col-md-4">
    <%= form.label :'Telefone' %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :phone, class: 'form-control',  required: 'required', placeholder: 'Digite o Telefone', id: :subscription_phone %>
    </div>
  </div>

  <div class="field col-md-4">
    <%= form.label :'E-mail' %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :email, class: 'form-control', required: 'required', placeholder: 'Digite o E-mail', id: :subscription_email %>
    </div>
  </div>

  <div class="field col-md-4">
    <%= form.label :'Escolaridade' %><br>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :schooling, class: 'form-control', required: 'required', placeholder: 'Escolaridade',  id: :subscription_schooling %>
    </div>
  </div>

  <div class="field col-md-4">
    <%= form.label :'Experiencia' %><br>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.check_box :experienced, id: :subscription_experienced %>
    </div>
  </div>

  <div class="field col-md-12">
    <%= form.label :'Descreva a sua experiencia' %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_area :experience_description, class:'form-control', placeholder: 'Descreva sua experiencia',
     id: :subscription_experience_description %>
    </div>
  </div>

  <div class="field col-md-12">
    <%= form.label :'Assinatura Digital' %>
    <div class='input-group'>
    <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
    <%= form.text_field :signature, class: 'form-control', required: 'required', placeholder: 'Digite sua assinatura Digital',  id: :subscription_signature %>
    </div>
  </div>

  <div class="actions col-md-12">
    <%= form.submit nil, class: 'btn btn-primary btn-lg top' %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthdate</th>
      <th>Artistic name</th>
      <th>Age</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Address</th>
      <th>City</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Schooling</th>
      <th>Experienced</th>
      <th>Experience description</th>
      <th>Signature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.name %></td>
        <td><%= subscription.birthdate %></td>
        <td><%= subscription.artistic_name %></td>
        <td><%= subscription.age %></td>
        <td><%= subscription.cpf %></td>
        <td><%= subscription.rg %></td>
        <td><%= subscription.address %></td>
        <td><%= subscription.city %></td>
        <td><%= subscription.phone %></td>
        <td><%= subscription.email %></td>
        <td><%= subscription.schooling %></td>
        <td><%= subscription.experienced %></td>
        <td><%= subscription.experience_description %></td>
        <td><%= subscription.signature %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<ul class='list-unstyled text-center'> 
  <li><h1 class='text-center'><i class='glyphicon glyphicon-search'></i> INSCREVA-SE</h1></li>
  <li class='text-center'><p>Inscreva-se no nosso processo seletivo.</p></li>
  <li><hr></li>
</ul>

<%= render 'form', subscription: @subscription %>
<%= link_to 'Back', subscriptions_path, class: 'btn btn-default btn-lg top pull-left' %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subscription.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @subscription.birthdate %>
</p>

<p>
  <strong>Artistic name:</strong>
  <%= @subscription.artistic_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @subscription.age %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @subscription.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @subscription.rg %>
</p>

<p>
  <strong>Address:</strong>
  <%= @subscription.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @subscription.city %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @subscription.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<p>
  <strong>Schooling:</strong>
  <%= @subscription.schooling %>
</p>

<p>
  <strong>Experienced:</strong>
  <%= @subscription.experienced %>
</p>

<p>
  <strong>Experience description:</strong>
  <%= @subscription.experience_description %>
</p>

<p>
  <strong>Signature:</strong>
  <%= @subscription.signature %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>